version: "3.8"

services:
  # Django Backend Service (Using Neon Database)
  backend:
    build:
      context: ./Blog
      dockerfile: Dockerfile
    container_name: blog_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Blog:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_Qo3egb0lGWfJ@ep-divine-sunset-ah9n3pgz-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    networks:
      - blog_network

  # React Frontend Service
  frontend:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
    container_name: blog_frontend
    volumes:
      - ./blog-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - blog_network
    stdin_open: true
    tty: true

# Custom network for container communication
networks:
  blog_network:
    driver: bridge
