# Generated by Django 5.2 on 2025-10-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
